# "sudo:required" means "docker available"
sudo: required
dist: trusty
services:
- docker

language: go
go:
  - 1.7

env:
    global:
        - ORTHANC_VERSION="Orthanc-1.1.0"
        - ORTHANC_BUILD="$HOME/.cache/${ORTHANC_VERSION}Build"
        - DOCKER_DIR="$HOME/.cache/docker"

cache:
    directories:
        - $ORTHANC_BUILD
        - $DOCKER_DIR

before_install:
  - go get github.com/tonistiigi/buildcache/cmd/buildcache
  - which buildcache

install:
# Orthanc requirements
    - sudo apt-get update

script:
- pwd
- ls -al
- docker version
- test -f "$DOCKER_DIR/latest_cache.tar.gz" && sudo docker load -i "$DOCKER_DIR/latest_cache.tar.gz"
- docker images -a
- docker build -t my_image .
#- docker save my_image > "$DOCKER_DIR/image.tar"
- sudo `which buildcache` save -o "$DOCKER_DIR/latest_cache.tar.gz" my_image


after_success:
# Split out build steps to script to avoid yml parsing issues of the commands.
- bash -x ./build-trigger.sh Tag "${TRAVIS_TAG}" "${DOCKERHUB_TRIGGER_URL}"
