# "sudo:required" means "docker available"
sudo: false
dist: trusty

script:
- ./test/test-ci.sh

after_success:
# Split out build steps to script to avoid yml parsing issues of the commands.
- bash -x ./build-trigger Tag "${TRAVIS_TAG}" "${TRIGGER_URL}"
