# "sudo:required" means "docker available"
sudo: required
dist: trusty
services:
- docker

env:
    global:
        - ORTHANC_VERSION="Orthanc-1.1.0"
        - ORTHANC_BUILD="$HOME/.cache/${ORTHANC_VERSION}Build"
        - DOCKER_DIR="$HOME/.cache/docker"

cache:
    directories:
        - $ORTHANC_BUILD
        - $DOCKER_DIR

install:
# Orthanc requirements
    - sudo apt-get update

script:
- pwd
- ls -al
- docker version
- test -f "$DOCKER_DIR/image.tar" && sudo docker load -i "$DOCKER_DIR/image.tar" || true
- docker images -a
- docker build -t my_image .
#- docker save my_image > "$DOCKER_DIR/image.tar"
- docker save -o "$DOCKER_DIR/image.tar" $(docker history -q my_image | grep -v '<missing>')

after_success:
# Split out build steps to script to avoid yml parsing issues of the commands.
- bash -x ./build-trigger.sh Tag "${TRAVIS_TAG}" "${DOCKERHUB_TRIGGER_URL}"
