# "sudo:required" means "docker available"
sudo: required


env:
    global:
        - ORTHANC_VERSION="Orthanc-1.1.0"
        - ORTHANC_BUILD="${ORTHANC_VERSION}Build"

cache:
    directories:
        - $ORTHANC_BUILD

install:
# Orthanc requirements
    - sudo apt-get update
    - sudo apt-get install build-essential unzip cmake mercurial
      uuid-dev libcurl4-openssl-dev liblua5.1-0-dev
      libgtest-dev libpng-dev libsqlite3-dev libssl-dev libjpeg-dev
      zlib1g-dev libdcmtk2-dev libboost1.48-all-dev libwrap0-dev
      libcharls-dev

script:
- ./test/test-ci.sh

after_success:
# Split out build steps to script to avoid yml parsing issues of the commands.
- bash -x ./build-trigger.sh Tag "${TRAVIS_TAG}" "${DOCKERHUB_TRIGGER_URL}"
